### ISSUE TITLE
A800 OOM Error in training diffusion policy

### ISSUE THREAD

**Issue by eternity123-null** [arth-shukla/mshab#19]
Hello @arth-shukla! I try to train dp on a800, but the code seems have cuda memory leakage problem. At the beginning, the training only consume 
12G gpu memory , but after training 15%, the memory becomes to 65G and then finally CUDA oom. You said you train one diffusion policy on a single 4090, I just couldn't figure out what happend.. 

![Image](https://github.com/user-attachments/assets/5cc168e9-2567-4b58-aec4-2295ed5cf872)

```
#!/usr/bin/bash

export NCCL_P2P_DISABLE=1 
# export CUDA_VISIBLE_DEVICES=0,2,3

SEED=0

TRAJS_PER_OBJ=all
MAX_IMAGE_CACHE_SIZE=400_000   # safe num for about 64 GiB system memory
num_dataload_workers=10
num_iterations=1_000_000

TASK=set_table
SPLIT=train


WANDB=True
TENSORBOARD=False
if [[ -z "${MS_ASSET_DIR}" ]]; then
    MS_ASSET_DIR="$HOME/.maniskill"
fi
WORKSPACE="mshab_exps"
PROJECT_NAME="MS-HAB-RCAD-dp"

# 定义 SUBTASK 和 OBJ 的组合
declare -a SUBTASKS=("pick" "place" "open" "open" "close" "close")
declare -a OBJS=("all" "all" "fridge" "kitchen_counter" "fridge" "kitchen_counter")


GPUS=(0 2 3)
NUM_GPUS=${#GPUS[@]}


pids=()


for idx in "${!SUBTASKS[@]}"; do
    SUBTASK=${SUBTASKS[$idx]}
    OBJ=${OBJS[$idx]}

   
    LOGFILE="train_${SUBTASK}_${OBJ}.log"

    GPU=${GPUS[$(( idx % NUM_GPUS ))]}
    export CUDA_VISIBLE_DEVICES=$GPU
    echo "分配 GPU $GPU 给任务：$SUBTASK + $OBJ, 输出写入 $LOGFILE"

    ENV_ID="$(echo $SUBTASK | sed 's/\b\(.\)/\u\1/g')SubtaskTrain-v0"
    GROUP=$TASK-rcad-dp-$SUBTASK
    EXP_NAME="$ENV_ID/$GROUP/dp-$SUBTASK-$OBJ-local-trajs_per_obj=$TRAJS_PER_OBJ"
    
    RESUME_LOGDIR="$WORKSPACE/$EXP_NAME"
    RESUME_CONFIG="$RESUME_LOGDIR/config.yml"


    if [[ $SUBTASK == "open" || $SUBTASK == "close" ]]; then
        data_dir_fp="$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange-dataset/$TASK/$SUBTASK/$OBJ.h5"
    else
        data_dir_fp="$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange-dataset/$TASK/$SUBTASK"
    fi


    args=(
        "logger.wandb_cfg.group=$GROUP"
        "logger.exp_name=$EXP_NAME"
        "seed=$SEED"
        "eval_env.env_id=$ENV_ID"
        "eval_env.task_plan_fp=$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/$TASK/$SUBTASK/$SPLIT/$OBJ.json"
        "eval_env.spawn_data_fp=$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/$TASK/$SUBTASK/$SPLIT/spawn_data.pt"
        "eval_env.stack=2"
        "algo.num_iterations=$num_iterations"
        "algo.trajs_per_obj=$TRAJS_PER_OBJ"
        "algo.data_dir_fp=$data_dir_fp"
        "algo.max_image_cache_size=$MAX_IMAGE_CACHE_SIZE"
        "algo.num_dataload_workers=$num_dataload_workers"
        "algo.eval_freq=5000"
        "algo.log_freq=1000"
        "algo.save_freq=5000"
        "eval_env.make_env=True"
        "eval_env.num_envs=252"
        "eval_env.max_episode_steps=200"
        "eval_env.record_video=False"
        "eval_env.info_on_video=False"
        "eval_env.save_video_freq=1"
        "logger.wandb=$WANDB"
        "logger.tensorboard=$TENSORBOARD"
        "logger.project_name=$PROJECT_NAME"
        "logger.workspace=$WORKSPACE"
    )

    if [ -f "$RESUME_CONFIG" ] && [ -f "$RESUME_LOGDIR/models/latest.pt" ]; then
        echo "RESUMING for $SUBTASK + $OBJ"
        SAPIEN_NO_DISPLAY=1 python -m mshab.train_diffusion_policy "$RESUME_CONFIG" RESUME_LOGDIR="$RESUME_LOGDIR" \
            logger.clear_out="False" \
            logger.best_stats_cfg="{eval/success_once: 1, eval/return_per_step: 1}" \
            "${args[@]}" > "$LOGFILE" 2>&1 &
    else
        echo "STARTING for $SUBTASK + $OBJ"
        SAPIEN_NO_DISPLAY=1 python -m mshab.train_diffusion_policy configs/dp_pick.yml \
            logger.clear_out="True" \
            logger.best_stats_cfg="{eval/success_once: 1, eval/return_per_step: 1}" \
            "${args[@]}" > "$LOGFILE" 2>&1 &
    fi


    pids+=($!)
    

    if (( (idx+1) % NUM_GPUS == 0 )); then
        wait "${pids[@]}"
        pids=()
    fi
done


if [ ${#pids[@]} -gt 0 ]; then
    wait "${pids[@]}"
fi
```

Then, after training 3 hours `16%|█▌        | 160000/1000000 [3:36:46<11:41:55, 19.95it/s]`  It got an error:

```

16%|█▌        | 160000/1000000 [3:36:46<11:41:55, 19.95it/s]
[2025-04-04 01:53:11.486] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-04-04 01:53:11.489] [SAPIEN] [critical] /buildAgent/work/eb2f45c4acc808a0/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp
[2025-04-04 01:53:12.274] [SAPIEN] [critical] GPU cudaMainGjkEpa or prepareLostFoundPairs kernel fail! 700
[2025-04-04 01:53:12.274] [SAPIEN] [critical] memcpy failed fail! 3 700 
[2025-04-04 01:53:12.274] [SAPIEN] [critical] memcpy failed fail! 3 700 
[2025-04-04 01:53:12.274] [SAPIEN] [critical] SynchronizeStreams cuEventRecord failed with error 700
[2025-04-04 01:53:12.274] [SAPIEN] [critical] SynchronizeStreams cuStreamWaitEvent failed with error 700
[2025-04-04 01:53:12.276] [SAPIEN] [critical] GPU contactConstraintPrepare fail to launch kernel!!
.......
[2025-04-04 01:53:13.095] [SAPIEN] [critical] PhysX Internal CUDA error. Simulation can not continue! Error code 700!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/chendong/maniskill/mshab/mshab/train_diffusion_policy.py", line 597, in <module>
    obs, rew, terminated, truncated, info = eval_envs.step(
                                            ^^^^^^^^^^^^^^^
  File "/home/chendong/maniskill/mshab/mshab/envs/wrappers/vector/record_episode_statistics.py", line 135, in step
    ) = self.env.step(actions)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/maniskill/ManiSkill/mani_skill/vector/wrappers/gymnasium.py", line 112, in step
    obs, rew, terminations, truncations, infos = self._env.step(actions)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/openpi/.venv/lib/python3.11/site-packages/gymnasium/core.py", line 591, in step
    return self.env.step(self.action(action))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/maniskill/mshab/mshab/envs/wrappers/observation.py", line 213, in step
    obs, rew, term, trunc, info = super().step(*args, **kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/openpi/.venv/lib/python3.11/site-packages/gymnasium/core.py", line 461, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/openpi/.venv/lib/python3.11/site-packages/gymnasium/core.py", line 522, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/maniskill/ManiSkill/mani_skill/utils/registration.py", line 161, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/openpi/.venv/lib/python3.11/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chendong/maniskill/ManiSkill/mani_skill/envs/sapien_env.py", line 935, in step
    self._elapsed_steps += 1
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by eternity123-null** [comment]
I have now found that during the latter part of the training, the CUDA memory occupied will increase during each evaluation step, and the CUDA memory is not released after the evaluation is completed. However, during the first half of the training, the CUDA memory occupied basically does not increase.

**Comment by arth-shukla** [comment]
@eternity123-null Hm that's interesting. I previously ran DP for about an hour and didn't find any weird behavior, however this was only for an 1h40m: https://github.com/arth-shukla/mshab/issues/9

I also trained PPO overnight (14h) and don't seem to have the exploding CUDA memory issue: https://wandb.ai/arth-shukla/MS-HAB-RCAD-Pick-tidy_house-ppo/overview

It's hard to say what caused this since I didn't reproduce. Does memory balloon after a deterministic number of evals, or is it after some specific wall time?

---

Side note: if you aren't already, I'd recommend the training args from https://github.com/arth-shukla/mshab/issues/9, especially `algo.truncate_trajectories_at_success=True`, since this improves perf.

**Comment by StoneT2000** [comment]
is the eval env reconfiguring maybe?

**Comment by eternity123-null** [comment]
> Does memory balloon after a deterministic number of evals

Yes, it usually balloon after 120\~130k training steps, that is 25\~26 evals

> Also, does this happen when you run one job on one GPU w/o the round robin allocation?

I have three A800，there are only one training task on one gpu all the time.

I also tried your training config (only change num_dataload_workers to 8, and add torch.cuda.empty_cache() after eval step), it also OOM after 125k steps. I think the most easy way to reproduce is just training more steps lol.
 
Below is my [wandb logs for place-all training](https://wandb.ai/1298842997-shanghai-jiao-tong-university/MS-HAB-RCAD-dp/runs/stp15hwz?nw=nwuser1298842997)

**Comment by arth-shukla** [comment]
@eternity123-null I was able to reproduce the error. Since it's happening in the DP script but not the PPO script, it's prob not an env issue, and the eval env shouldn't be reconfiguring. Will test some more and whittle down the issue.

**Comment by arth-shukla** [comment]
@eternity123-null Sorry for the delayed reply. I checked with 189 envs and the memory use seems to stay stable. Can you try setting `eval_env.num_envs=189` and see if that works?

**Comment by eternity123-null** [comment]
Thanks for your effort, I'll try this.

**Comment by eternity123-null** [comment]
It works well now. Thanks again. However, the success rate after training the Diffusion Policy for pick all skill is currently very low, barely reaching 20%. Have you test other skills except place_all skill?

![Image](https://github.com/user-attachments/assets/35f16789-8688-4211-a173-a058457daa5d)

**Comment by arth-shukla** [comment]
@eternity123-null Our baseline results ([Appendix A.4.6](https://arxiv.org/html/2412.13211v3#:~:text=A.4.6%20Diffusion%20Policy%20Baselines)) were higher, but didn't solve the task. Recommended args below (worth tuning act/pred horizon to be shorter).

Also worth noting the baseline DP implementation uses standard DDPM, a small encoder, depth only, and a small UNet. So, there's def room for improvement by using newer algos, archs, etc.

```
#!/usr/bin/bash

SEED=0

TRAJS_PER_OBJ=all
MAX_IMAGE_CACHE_SIZE=all
num_dataload_workers=2
num_iterations=1_000_000

TASK=set_table
SUBTASK=place
SPLIT=train
OBJ=all

# shellcheck disable=SC2001
ENV_ID="$(echo $SUBTASK | sed 's/\b\(.\)/\u\1/g')SubtaskTrain-v0"
WORKSPACE="mshab_exps"
GROUP=$TASK-rcad-dp-$SUBTASK
EXP_NAME="$ENV_ID/$GROUP/dp-$SUBTASK-$OBJ-local-trajs_per_obj=$TRAJS_PER_OBJ"
# shellcheck disable=SC2001
PROJECT_NAME="MS-HAB-RCAD-dp-issue-9"

WANDB=True
TENSORBOARD=True
if [[ -z "${MS_ASSET_DIR}" ]]; then
    MS_ASSET_DIR="$HOME/.maniskill"
fi

RESUME_LOGDIR="$WORKSPACE/$EXP_NAME"
RESUME_CONFIG="$RESUME_LOGDIR/config.yml"

if [[ $SUBTASK == "open" || $SUBTASK == "close" ]]; then
    data_dir_fp="$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange-dataset/$TASK/$SUBTASK/$OBJ.h5"
else
    data_dir_fp="$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange-dataset/$TASK/$SUBTASK"
fi

args=(
    "logger.wandb_cfg.group=$GROUP"
    "logger.exp_name=$EXP_NAME"
    "seed=$SEED"
    "eval_env.env_id=$ENV_ID"
    "eval_env.task_plan_fp=$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/$TASK/$SUBTASK/$SPLIT/$OBJ.json"
    "eval_env.spawn_data_fp=$MS_ASSET_DIR/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/$TASK/$SUBTASK/$SPLIT/spawn_data.pt"
    "algo.num_iterations=$num_iterations"
    "algo.trajs_per_obj=$TRAJS_PER_OBJ"
    #
    "algo.data_dir_fp=$data_dir_fp"
    "algo.max_image_cache_size=$MAX_IMAGE_CACHE_SIZE"
    "algo.num_dataload_workers=$num_dataload_workers"
    "algo.truncate_trajectories_at_success=True"
    #
    "eval_env.stack=2"
    "algo.obs_horizon=2"
    "algo.act_horizon=2"
    "algo.pred_horizon=4"
    #
    "algo.eval_freq=5000"
    "algo.log_freq=1000"
    "algo.save_freq=5000"
    "eval_env.make_env=True"
    "eval_env.num_envs=189"
    "eval_env.max_episode_steps=200"
    "eval_env.record_video=False"
    "eval_env.info_on_video=False"
    "eval_env.save_video_freq=1"
    "logger.wandb=$WANDB"
    "logger.tensorboard=$TENSORBOARD"
    "logger.project_name=$PROJECT_NAME"
    "logger.workspace=$WORKSPACE"
)

if [ -f "$RESUME_CONFIG" ] && [ -f "$RESUME_LOGDIR/models/latest.pt" ]; then
    echo "RESUMING"
    SAPIEN_NO_DISPLAY=1 python -m mshab.train_diffusion_policy "$RESUME_CONFIG" RESUME_LOGDIR="$RESUME_LOGDIR" \
        logger.clear_out="False" \
        logger.best_stats_cfg="{eval/success_once: 1, eval/return_per_step: 1}" \
        "${args[@]}"

else
    echo "STARTING"
    SAPIEN_NO_DISPLAY=1 python -m mshab.train_diffusion_policy configs/dp_pick.yml \
        logger.clear_out="True" \
        logger.best_stats_cfg="{eval/success_once: 1, eval/return_per_step: 1}" \
        "${args[@]}"
        
fi
```
